llm:
  provider: anthropic
  name: claude-3-5-haiku-latest

vector_store:
  provider: pinecone
  index_name: 02-project-index

embedding:
  provider: huggingface
  model: sentence-transformers/all-roberta-large-v1
  size: 1024
